### ISSUE TITLE
Flag to exit with non-zero code when timer is cancelled?

### ISSUE THREAD

**Issue by nathanielknight** [elpnt/cdown#2]
Hello, thanks for building this project! I get a lot of use out of it 🙂

What do you think about adding a flag that makes the timer exit with a non-zero code when it's cancelled (with `q`) instead of running out? My use case is having a countdown that triggers a notification on exit, but where I don't want to trigger the notification if the timer is cancelled.

If that's something you'd be interested in merging I'd be happy to put together a PR.

**Comment by elpnt** [comment]
Sorry I missed the issue! 🙇

It sounds good to exit with non-zero code.
I'll be waiting for your PR.
